customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('',views.Home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('login/',views.login,name='login'),
    path('customer_dashboard/', views.customer_dashboard , name='customer_dashboard'),
    path('cart/',views.cart,name='cart'),
    path('add_to_cart/<int:product_id>',views.add_to_cart ,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>',views.remove_from_cart, name='remove_from_cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('logout/',views.logout,name='logout'),
    path('search/',views.search,name='search')
]

essence/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from.import views
app_name='seller'
urlpatterns=[
    path('seller_home/',views.seller_home ,name='seller_home'),
    path('seller_login/',views.seller_login,name='seller_login'),
    path('seller_dashboard/',views.seller_dashboard, name='seller_dashboard'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('view_products/', views.view_products, name='view_products'),
    path('delete_product/<int:product_id>', views.delete_product, name='delete_product'),
    path('update_product/<int:product_id>', views.update_product, name='update_product'),
    path('sellerlogout/',views.sellerlogout,name='sellerlogout')
    
]

customer/models.py
from django.db import models
from seller.models import *
# Create your models here.
class CustomerRegistration(models.Model):
    Name=models.TextField(max_length=100,null=True)
    Email=models.TextField(max_length=100,null=True)
    Password=models.TextField(max_length=100,null=True)


class Cart(models.Model):
    customer=models.ForeignKey(CustomerRegistration,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    quantity=models.PositiveIntegerField(default=1)

customer/views.py
from django.shortcuts import render,redirect
from.models import *
from seller.models import *
# Create your views here.
def Home(request):
    return render(request,'customer/home.html')

def signup(request):
    if request.method=='POST':
        Name=request.POST['name']
        Email=request.POST['email']
        Password=request.POST['password']
        customer=CustomerRegistration(Name=Name,Email=Email,Password=Password)
        customer.save()
        return redirect('customer:login')
    return render(request,'customer/signup.html')


def login(request):
    if request.method=='POST':
        Name=request.POST['name']
        Email=request.POST['email'] 
        Password=request.POST['password']
        try:
            cust=CustomerRegistration.objects.get(Email=Email , Password=Password)
            request.session['customer']=cust.id
            return redirect('customer:customer_dashboard')
        except CustomerRegistration.DoesNotExist:

        # if CustomerRegistration.objects.filter(Email=Email,Password=Password).exists():
        #     return redirect('customer:customer_dashboard')
        # else:
            return render(request ,'customer/login.html',{'msg':'INVALID USER OR EMAIL'})
    return render(request,'customer/login.html')


def customer_dashboard(request):
    if 'customer' in request.session:
      products=Product.objects.all()
      return render(request,'customer/customer_dashboard.html',{'products':products})
    else:
        return render(request,'customer/home.html')
 

def add_to_cart(request,product_id):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
        cust=CustomerRegistration.objects.get(id=customer_id)
        if request.method=='POST':
           product=Product.objects.get(id=product_id)
           cart_item,created=Cart.objects.get_or_create(product=product,customer=cust)
           if not created:
             cart_item.quantity+=1
             cart_item.save()
        return redirect('customer:cart')
    else:
        return render(request,'customer/home.html')
 

def cart(request):
    if 'customer' in request.session:

        customer_id=request.session.get('customer')
        cust=CustomerRegistration.objects.get(id=customer_id)
        cart_items=Cart.objects.filter(customer=cust)
        total_price=sum(item.product.price*item.quantity for item in cart_items)
        total_price_per_item=[]
        grand_total=0
        for item in cart_items:
           item_total=item.product.price*item.quantity
           total_price_per_item.append({'item':item,'total':item_total})
           grand_total+=item_total
        return render(request,'customer/cart.html',{'cart_items':cart_items,'grand_total':grand_total,'total_price':total_price})
    else:
        return render(request,'customer/home.html')
 


def remove_from_cart(request,product_id):
    if 'customer' in request.session:

        customer_id=request.session.get('customer')
        cust=CustomerRegistration.objects.get(id=customer_id)
        product=Product.objects.get(id=product_id)
        cart_item=Cart.objects.get(product=product,customer=cust)
        cart_item.delete()
        return redirect('customer:cart')


def checkout(request):
    return render(request,'customer/checkout.html')

def logout(request):
    if 'customer' in request.session:
        del request.session['customer']
        return render(request,'customer/home.html') 
    else:
        return render(request,'customer/home.html') 


def search(request):
    
    if 'keyword' in request.GET:
        keyword= request.GET['keyword']
        if keyword:
            product=Product.objects.filter(description__icontains=keyword)
            context={
              'products':product 
            }
            return render(request,'customer/customer_dashboard.html',context) 
        else :
            return render(request,'customer/home.html') 
    else :
        return render(request,'customer/home.html') 
    

customer/templates/customer/cart.html
{% extends 'customer/home.html' %}
{% load static %}
{% block content %}
<br><br><br>
<div class="container-fluid" style="background-color: plum; text-align: center;"><div class="row" ><div class="col-12"><h2>CART</h2></div></div></div>

{% for item in cart_items %}

<div class="container-fluid" style="background-color:  rgb(222, 195, 222) ; text-align: center;">
    <div class="row"><div class="col-4"></div>
    <div class="col-4">
    <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ item.product.image.url }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"> {{item.product.product_name}} </h5>
          <p class="card-text"> Price=Rs. {{item.product.price}} </p>
          <p class="card-text">  Quantity= {{item.quantity}} </p>

          <form action="{% url 'customer:remove_from_cart' item.product.id %}" method="post">
            {% csrf_token %}
            
            <button type="submit" class="btn btn-dark">DELETE</button>
          </form>
        </div>
      </div>
    </div>
  </div></div>
<div class="col-4"></div></div>
</div>
{% endfor %}
<div class="container-fluid" style="text-align: end;" ><div class="row" ><div class="col-12"><h4>TOTAL SUM=Rs.{{grand_total}}</h4><a  class="btn btn-dark" href="{% url 'customer:checkout' %}">CHECK OUT</a><br><br></div></div></div>
{% endblock %}

customer/templates/customer/checkout.html
{% extends 'customer/home.html' %}
{% load static %}
<br><br><br>
{% block content %}
<div class="container-fluid" ><div class="row"><div class="col-12" style="height: 650px; background-color: rgb(222, 195, 222) ;"></div></div></div>


{% endblock %}

customer/templates/customer/customer_dashboard.html
{% extends 'customer/home.html' %}
{% load static %}
{% block content %}
<br><br><br>
<div class="row">
    <div class="col-6"><div id="carouselExampleAutoplaying" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="250" >
            <img  style="height: 450px;" src="{% static 'images/WOMEN11.jpg'%}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item" data-bs-interval="250" >
            <img  style="height: 450px;" src="{% static 'images/WOMEN22.jpg'%}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item" data-bs-interval="250" >
            <img style="height: 450px;" src="{% static 'images/women33.jpg'%}" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div></div>
    <div class="col-6" style="background-color: plum;display: flex; justify-content: center; align-items: center; " ><h2 style="color:white ; ">Meet Our All New Fruit Babies</h2></div>
</div>
  
<!-- -------------- -->


<div class="row" >
    {% for product in products %}
     <div class="col-3 ">
        <div class="card mx-auto mt-5 " style="width: 18rem;">
        <img src="{{product.image.url}}" class="card-img-top  " alt="...">
            <div class="card-body">
              <h5 class="card-title">{{product.product_name}}</h5>
              <h5 class="card-title">{{product.price}}</h5>
              <form action="{% url 'customer:add_to_cart' product.id %}" method="post">
                {% csrf_token %}
                <div class="quantity" style="display: none;">
                  <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                </div>
                <button type="submit" style="background-color: lightcoral; color: white;">ADD TO CART</button>
              </form>
              
              </div>
        </div>
    </div>
    {% endfor %}
</div>



{% endblock %}

customer/templates/customer/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Essence</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   
  <style>
    
    


  </style>
</head>
  <body>
<div class="container-fluid">
    <div class="row" >
      <div class="col-12" >
        <nav   class="navbar  navbar-light bg-white fixed-top " >
        <div class="container-fluid">
          <img  style="height: 50px; width: 150px; " src="{% static 'images/logo12.jpg'%}" alt="" >
          
          <form class="d-flex mt-3" role="search" style=" margin-left: 700px;" action="{% url 'customer:search'%}" method="get">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
            <button class="btn btn-dark" type="submit">Search</button>
            
          </form>
          

          
          <!-- <a href=""><img  style="height: 40px; width: 40px;" src="{% static 'images/search_icon.jpg'%}" alt=""  ></a> -->
          <a  href="{% url 'customer:login' %}"><img  style="height: 40px; width: 40px;  " src="{% static 'images/user_icon.jpg'%}" alt="" ></a>
          <a href="{% url 'customer:cart' %}"><img  style="height: 40px; width: 40px;" src="{% static 'images/cartimg.jpg'%}" alt=""  ></a>
          <a href="{% url 'customer:logout' %}" class="btn btn-dark" >Logout</a>
          

          
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Essence</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'customer:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'customer:signup' %}">Sign up</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'seller:seller_home' %}">Seller </a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Products
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Moisturizer</a></li>
                    <li><a class="dropdown-item" href="#">Cleanser</a></li>
                    <li><a class="dropdown-item" href="#">Serum</a></li>
                    <li><a class="dropdown-item" href="#">Sunscreen</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item"  href="#about">About Us </a></li>
                  </ul>
                </li>
              </ul>
              <form class="d-flex mt-3" role="search"  action="{% url 'customer:search'%}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </div>
      </nav></div>
    </div>
{% block content %}
<!-- CALOUSAL -->
<br><br><br>
<div class="row">
    <div class="col-12"><div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img  style="height:450px ;" src="{% static 'images/Screenshot.jpg'%}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img  style="height: 450px;" src="{% static 'images/callousal_pink.jpg'%}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img style="height: 450px;"  src="{% static 'images/carousel_girls1.jpg'%}" class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div></div>
</div>


<!-- -->
<br>
<div class="container-fluid" >
<div class="row" ><div class="col-12" style="background-color: lightpink;  color: #FFFFFF;  text-align: center;  font-weight: 1000;">OUR PRODUCTS</div></div></div>


<!-- CARDS -->

<br>
<div class="container-fluid">
<div class="row" style= "text-align: center;">
  <div class="col-3"  ><div class="card mx-auto" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'images/moist_card.jpg'%}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Moisturizer</h5>
    <p class="card-text"></p>
    <!-- <a href="#" class="btn btn-primary" style="background-color:lightcoral;border: lightcoral;">Go somewhere</a> -->
  </div>
 </div></div>


  <div class="col-3" ><div class="card mx-auto" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'images/facewash_card1.jpg'%}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Cleanser</h5>
    <p class="card-text"></p>
    <!-- <a href="#" class="btn btn-primary" style="background-color:lightcoral;border: lightcoral;">Go somewhere</a> -->
  </div>
  </div></div>

  <div class="col-3"><div class="card mx-auto" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'images/serum12.jpg'%}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Serum</h5>
    <p class="card-text"></p>
    <!-- <a href="#" class="btn btn-primary" style="background-color:lightcoral;border: lightcoral;">Go somewhere</a> -->
  </div>
  </div></div>

  <div class="col-3"><div class="card mx-auto" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'images/sunscreen1.jpg' %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Sunscreen</h5>
    <p class="card-text"></p>
    <!-- <a href="#" class="btn btn-primary" style="background-color:lightcoral; border: lightcoral;">Go somewhere</a> -->
  </div>
  </div></div>


</div>
</div>

<!-- -------------- -->

<br>
<div class="container-fluid" >
<div class="row" ><div class="col-12" id="about" style="background-color: lightpink;  color: #FFFFFF;  text-align: center;  font-weight: 1000;">UNLOCK THE GOODNESS OF REAL FRUIT EXTRACTS</div></div></div>
  

<!-- -------------- -->


<!-- About Us -->
<br>
<div class="container-fluid" style= "text-align: center;"  ><div class="row"><div class="col-6"><img   style="height: 500px; width: 600px;" src="{% static 'images/all2.jpg' %}" alt=""></div>
<div class="col-6"  ><h2 >About Us</h2><hr><br>
<h4>Fruit Forward. Clinically Effective. Glowing Skin.</h4><br>
<h6>Your go-to brand for sensorial skincare innovations that deliver clinical effective results for healthy and glowing skin. We create gentle and effective formulas for better skin.</h6><br>
<h4>We are committed to sustainability.</h4><br>
<h6>We're constantly working to reduce our environmental footprints, by going carbon neutral, using eco-concious pakaging and offering a send-back recycling program.</h6><br>
<h4>We keep it real.</h4><br>
<h6>We celebrate real, unretouched skin and pledge to never use words that encourage unrealistic skin goals like perfect, ageless, flawless.</h6>

</div>
</div></div><br>
  
<!-- -------------- -->

  


<br>
<div class="container-fluid" >
<div class="row" ><div class="col-12" style="background-color: lightpink;  color: #FFFFFF;  text-align: center;  font-weight: 1000;">GOOD SKIN ALL DAY</div></div></div>
  
<!-- -------------- -->

<!-- VIDEO -->


<br>
<div class="container-fluid" >
  <div class="row">
    <div class="col-6" style= "text-align: right;"><video height="550px"  loop autoplay muted>
      <source src="{% static 'video/video3.mp4'%}" type="video/mp4">
    </video></div>
    <div class="col-6" style= "text-align: left;"><img style="height:550px; width:350px;" src="{% static 'images/avacado_serum.jpg'%}" alt=""></div>
  </div>
</div>




<!-- -------------- -->
{% endblock %}





<!-- BOTTTOM NAVBAR -->

<div class="container-fluid" style="background-color: plum;"><br>
  <div class="row" style="text-align: center;">

    <div class="col-4" ><h5>About</h5><p>About Us</p></div> 
    <div class="col-4"><h5>Support</h5><p>Contact Us</p></div>
    <div class="col-4"><h5>Connect With Us</h5><img style="height: 50px;" src="{% static 'images/Instagram.webp' %}"  alt=""><img style="height: 50px;" src="{% static 'images/FB.webp' %}" alt=""><img style="height: 50px;" src="{% static 'images/Twitter.webp' %}" alt=""></div>

</div></div>





  









</div>
<script src="{% static 'script/login.js' %}"></script>
       
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/customer/login.html
{% extends 'customer/home.html' %}
{% block content %}
<br><br><br>
<div class="container-fluid" style="background-color: rgb(222, 195, 222);" >
    <div class="row" > 
    <div class="col-4"></div>
    <div class="col-4" >
    <form  method="post" style="text-align: center;" onsubmit="return validate_login()">
    {% csrf_token %} 
      <br>
        <h3 style="font-weight: 500; ">Login</h3>
        <br>
        <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email">
    </div><br>
    <div class="form-group">
        <label for="exampleInputPassword1">Username</label>
        <input type="text" class="form-control" id="exampleInputPassword1"  name="name">
      </div><br>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="password" name="password" >
    </div><br>
    <label for="exampleInputPassword1"><p style="color: deeppink;" id="msg">{{msg}}</p></label>
    
  <br>
    <button  type="submit" class="btn btn-primary" style=" background-color: lightcoral; border: lightcoral; width:480px;">Login</button><br><br>
    <h5>New Customer ?</h5><br>
    <a href="{% url 'customer:signup' %}" style="text-decoration: none;"  ><div style=" background-color: lightcoral; height: 35px; width: 480px; color:#FFFF; border-radius: 5px; ">Sign up</div></a>

    <br><br><br><br>


</form></div></div></div>
{% endblock %}

customer/templates/customer/signup.html
{% extends 'customer/home.html'%}
{% block content%}
<br><br><br>

<div class="container-fluid" style="background-color: rgb(222, 195, 222);" >
    <div class="row" > 
    <div class="col-4"></div>
    <div class="col-4" >
    <form  method="post" style="text-align: center;">
     {% csrf_token %}   
     <br>
        <h3 style="font-weight: 500; ">Sign Up</h3>
        <br>
        <div class="form-group">
      <label for="exampleInputEmail1">Email</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
    </div><br>
    <div class="form-group">
        <label for="exampleInputPassword1">Username</label>
        <input type="text" class="form-control" id="exampleInputPassword1" name="name">
      </div><br>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="password" >
    </div><br>
    <div class="form-group">
        <label for="exampleInputPassword1"> Confirm Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
      </div>
    
  <br><br>
    <button type="submit" class="btn btn-primary" style=" background-color: lightcoral; border: lightcoral; width:480px;">Sign Up</button><br><br>
    <h5>Already have an account ?</h5><br>
    <a href="{% url 'customer:login' %}" style="text-decoration: none;"  ><div style=" background-color: lightcoral; height: 35px; width: 480px; color:#FFFF; border-radius: 5px; ">Login</div></a>

    <br><br><br><br>


</form></div></div></div>
{% endblock %}