customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('',views.Home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('login/',views.login,name='login'),
    path('customer_dashboard/', views.customer_dashboard , name='customer_dashboard'),
    path('cart/',views.cart,name='cart'),
    path('add_to_cart/<int:product_id>',views.add_to_cart ,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>',views.remove_from_cart, name='remove_from_cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('logout/',views.logout,name='logout'),
    path('search/',views.search,name='search')
]

essence/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from.import views
app_name='seller'
urlpatterns=[
    path('seller_home/',views.seller_home ,name='seller_home'),
    path('seller_login/',views.seller_login,name='seller_login'),
    path('seller_dashboard/',views.seller_dashboard, name='seller_dashboard'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('view_products/', views.view_products, name='view_products'),
    path('delete_product/<int:product_id>', views.delete_product, name='delete_product'),
    path('update_product/<int:product_id>', views.update_product, name='update_product'),
    path('sellerlogout/',views.sellerlogout,name='sellerlogout')
    
]

seller/models.py
from django.db import models

# Create your models here.
class SellerRegistration(models.Model):
    fullname=models.TextField(max_length=100,null=True)
    email=models.TextField(max_length=100,null=True)
    password=models.TextField(max_length=100,null=True)


    

    def  __str__(self):
        return self.fullname

class Category(models.Model):
    name=models.TextField(max_length=100,null=True)

    def __str__(self):
         return self.name
     
class Product(models.Model):
    product_name=models.TextField(max_length=100, null=True)     
    description=models.TextField(max_length=100, null=True)     
    price=models.FloatField(null=True) 
    category=models.ForeignKey(Category,on_delete=models.CASCADE) 
    image=models.ImageField(upload_to='products', null=True)    
    
   

seller/views.py
from django.shortcuts import render,redirect
from .models import*
# Create your views here.
def seller_home(request):
    return render (request,'seller/seller_home.html')


def seller_login(request):
    if request.method =='POST':
      Email=request.POST["email"]
      Password=request.POST["password"]
      try:
            sell=SellerRegistration.objects.get(email=Email , password=Password)
            request.session['seller']=sell.id
            return redirect('seller:seller_dashboard')
      except SellerRegistration.DoesNotExist:

    #   if SellerRegistration.objects.filter(email=Email,password=Password).exists():
    #      return redirect('seller:seller_dashboard')
    #   else:
         return render( request, 'seller/seller_login.html',{'msg':'INVALID EMAIL OR PASSWORD'})
    return render(request,'seller/seller_login.html')


def seller_dashboard(request):
    if 'seller' in request.session:
      return render(request,'seller/seller_dashboard.html')
    else:
        return render(request,'seller/seller_home.html')


def addproduct(request):
    categories=Category.objects.all()
    if request.method=='POST':
       name=request.POST.get('pdt_name')
       description=request.POST.get('description')
       price=request.POST.get('price')
       image=request.FILES['image']
       category=request.POST.get('category')
       cat=Category.objects.get(id=category)
       product=Product(product_name=name, description=description, price=price, image=image , category=cat)
       product.save()
    return render(request,'seller/addproduct.html',{'categories':categories})

def view_products(request):
   products=Product.objects.all()
   return render(request,'seller/view_products.html',{'products': products})

def delete_product(request,product_id):
   Product.objects.get(id=product_id).delete()
   return redirect('seller:view_products')

def update_product(request,product_id):
   categories=Category.objects.all()
   product=Product.objects.get(id=product_id)
   if request.method=='POST':
       name=request.POST.get('pdt_name')
       description=request.POST.get('description')
       price=request.POST.get('price')
       image=request.FILES.get('image')
       category=request.POST.get('category')
       cat=Category.objects.get(id=category)

       product.product_name=name
       product.description=description
       product.price=price
       product.image=image
       product.category=cat

       product.save()
       return redirect('seller:view_products')
   return render(request,'seller/update_product.html',{'categories': categories,'product': product})


def sellerlogout(request):
    if 'seller' in request.session:
        del request.session['seller']
        return render(request,'seller/seller_home.html') 
    else:
        return render(request,'seller/seller_home.html') 

seller/templates/seller/addproduct.html
{% extends 'seller/seller_home.html' %}
{% block content %}
<br><br><br>
<div class="container-fluid" style="background-color: rgb(222, 195, 222);">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h4>Add Products</h4><br>
            
            <div class="mb-3">
              <label for="name" class="form-label">Name</label>
              <input type="text" class="form-control" id="" name="pdt_name">
            </div>
             
            <div class="mb-3"> 
                <label for="" class="form-label">Description</label>
                <input type="text" class="form-control" id=""  name="description">
            </div>

            <div class="mb-3"> 
                <label for="" class="form-label">Price</label>
                <input type="text" class="form-control" id="" name="price">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Image</label>
                <input type="file" class="form-control" id="" name="image">
            </div>




            <div class="mb-3">
                <label for="" class="form-label">Category</label>
                <select class="form-select" aria-label=""  name="category">
                    {% for category in categories %}
                    <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                  </select>
            </div><br> 
        
            <button type="submit" style=" background-color: lightcoral; border: lightcoral; width:725px; height: 40px;  ; color:white;">ADD PRODUCT</button>
            
          </form>
        </div>
        <div class="col-3"></div>
    </div>
<br><br><br><br><br><br><br><br><br>
</div>
{% endblock %}

seller/templates/seller/seller_dashboard.html
{% extends 'seller/seller_home.html' %}
{% load static %}
{% block content %}

<br><br>
<div class="container-fluid" style="background-color: rgb(222, 195, 222); "  >
<br><br><br><br><br><br>
<div class="row">
<div class="col-3"></div>
<div class="col-3"><div class="card mx-auto" style="width: 18rem; text-align: center;">
  <img src="{% static 'images/about6.jpg' %}" class="card-img-top" alt="...">
  <div class="card-body" >

    <h5 class="card-title">ADD PRODUCTS</h5>
    <p class="card-text">Add products that are made with high quality ingredients and vegan certified.</p>
    <a href="{% url 'seller:addproduct' %}" class="btn btn-primary" style="background-color: lightcoral; border-color: lightcoral;">ADD PRODUCTS</a>
  
  </div>  
  </div>
</div>

<div class="col-3"><div class="card mx-auto" style="width: 18rem; text-align: center;">
  <img src="{% static 'images/about6.jpg' %}" class="card-img-top" alt="...">
  <div class="card-body" >

    <h5 class="card-title">VIEW PRODUCTS</h5>
    <p class="card-text">View products that are made with high quality ingredients and vegan certified.</p>
    <a href="{% url 'seller:view_products' %}" class="btn btn-primary" style="background-color: lightcoral; border-color: lightcoral;">VIEW PRODUCTS</a>
    </div>
  </div>
</div>
<div class="col-3"></div>



</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
</div>







{% endblock %}

seller/templates/seller/seller_home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Essence</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/home.css' %}">
  <style>
    
    


  </style>
</head>
  <body >
   <!-- NAVBAR -->
   
    <div class="container-fluid">
    <div class="row" >
      <div class="col-12" ><nav   class="navbar  navbar-light bg-white fixed-top " >
        <div class="container-fluid">
          <img  style="height: 50px; width: 150px;  " src="{% static 'images/logo12.jpg'%}" alt="" >
          <a  href="{% url 'seller:seller_login' %}"><img  style="height: 40px; width: 40px; margin-left: 1000px; " src="{% static 'images/user_icon.jpg'%}" alt="" ></a>
          <a href="{% url 'seller:sellerlogout' %}" class="btn btn-dark" >Logout</a>

          <!-- <a href=""><img  style="height: 40px; width: 40px;" src="{% static 'images/search_icon.jpg'%}" alt=""  ></a>
           -->
          <br><br>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Essence</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'customer:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'customer:signup' %}">Sign up</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'seller:seller_home' %}">Seller </a>
                </li>
                <!-- <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Products
                  </a> -->
                  <!-- <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Moisturizer</a></li>
                    <li><a class="dropdown-item" href="#">Cleanser</a></li>
                    <li><a class="dropdown-item" href="#">Serum</a></li>
                    <li><a class="dropdown-item" href="#">Sunscreen</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">About Us </a></li> -->
                  <!-- </ul> -->
                <!-- </li>
              </ul> -->
              <!-- <form class="d-flex mt-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form> -->
            </div>
          </div>
        </div>
      </nav></div>
    </div>

    <!-- -------------- -->

   {% block content %}
    <!-- MIDDLE -->
    <br><br><br>
      <div class="container-fluid" style="background-color: rgb(222, 195, 222); "  >
        <br><br><br><br><br><br><br>
        <div class="row">
        <div class="col-3"></div>
        <div class="col-3"><div class="card mx-auto" style="width: 18rem; text-align: center;">
          <img src="{% static 'images/about5.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body" >
        
            <h5 class="card-title"></h5>
            <a href="{% url 'seller:seller_dashboard'  %}" class="btn btn-primary" style="background-color: lightcoral; border-color: lightcoral;"> GO TO SELLER DASHBOARD</a>
          
          </div>  
          </div>
        </div>
        
        <div class="col-3"><div class="card mx-auto" style="width: 18rem; text-align: center;">
          <img src="{% static 'images/about5.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body" >
        
            <h5 class="card-title"></h5>
            <a href="{% url 'seller:seller_login'  %}" class="btn btn-primary" style="background-color: lightcoral; border-color: lightcoral;">SELLER LOGIN</a>
            </div>
          </div>
        </div>
        <div class="col-3"></div>
        
        
        
        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br>
        </div>
        
    
    <!-- -------------- -->
    </div></div></div>
    {% endblock %}


<!-- BOTTOM NAVBAR -->
    <div class="container-fluid" style="background-color: plum;"><br>
        <div class="row" style="text-align: center;">
          <div class="col-4" >
           <h5>About</h5><p>About Us</p></div> 
           <div class="col-4"><h5>Support</h5><p>Contact Us</p></div>
           <div class="col-4"><h5>Connect With Us</h5><img style="height: 50px;" src="{% static 'images/Instagram.webp' %}"  alt=""><img style="height: 50px;" src="{% static 'images/FB.webp' %}" alt=""><img style="height: 50px;" src="{% static 'images/Twitter.webp' %}" alt=""></div>

      
      </div></div>



<!-- -------------- -->

    </div>
    <script src="{% static 'script/seller_login.js' %}"></script>
           
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
    </html>

seller/templates/seller/seller_login.html
{% extends 'seller/seller_home.html' %}
{% block content %}
<br><br><br>
<div class="container-fluid" style="background-color: rgb(222, 195, 222);" >
    <div class="row" > 
    <div class="col-4"></div>
    <div class="col-4" >
    <form  method="post" onsubmit="return validate_seller_login()" style="text-align: center;">
        {% csrf_token %}
        <br>
        <h3 style="font-weight: 500; "> Seller Login</h3>
        <br>
        <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email">
    </div><br>
    
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="password" name="password" >
    </div><br>

    <div class="form-group">
    <label ><p id="msg" style="color: deeppink;">{{msg}}</p></label>
    </div>

    <br>
    <button type="submit" class="btn btn-primary" style=" background-color: lightcoral; border: lightcoral; width:480px;">Login</button><br><br>
    <h4>Already Logged In ?</h4><br>
    <a href="{% url 'seller:seller_dashboard' %}" style="text-decoration: none;"  ><div style=" background-color: lightcoral; height: 35px; width: 480px; color:#FFFF; border-radius: 5px; ">Go To Seller Dashboard</div></a>

    <br><br><br><br>


</form></div></div></div>
{% endblock %}

seller/templates/seller/update_product.html
{% extends 'seller/seller_home.html' %}
{% block content %}
<br><br><br>
<div class="container-fluid" style="background-color: rgb(222, 195, 222);">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h4>Update Products</h4><br>
            
            <div class="mb-3">
              <label for="name" class="form-label">Name</label>
              <input type="text" class="form-control" id="" name="pdt_name" value="{{product.product_name}}">
            </div>
             
            <div class="mb-3"> 
                <label for="" class="form-label">Description</label>
                <input type="text" class="form-control" id=""  name="description" value="{{product.description}}">
            </div>

            <div class="mb-3"> 
                <label for="" class="form-label">Price</label>
                <input type="text" class="form-control" id="" name="price" value="{{product.price}}">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Image</label>
                <input type="file" class="form-control" id="" name="image">
            </div>




            <div class="mb-3">
                <label for="" class="form-label">Category</label>
                <select class="form-select" aria-label=""  name="category" >
                    {% for category in categories %}
                    <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                  </select>
            </div><br> 
        
            <button type="submit" style=" background-color: lightcoral; border: lightcoral; width:725px; height: 40px;  ; color:white;">UPDATE PRODUCT</button>
            
          </form>
        </div>
        <div class="col-3"></div>
    </div>
<br><br><br><br><br><br><br><br><br>
</div>
{% endblock %}

seller/templates/seller/view_products.html
{% extends 'seller/seller_home.html' %}
{% block content %}
<br><br><br>
<div class="container-fluid" style="background-color: rgb(222, 195, 222);">
    
    <br><br>
    <div class="row">
        <div class="col-2"></div>
       <div class="col-8">
        <table class="table table-hover">
            <thead>
              <tr style="text-align: center; border: 1px solid black; border-collapse: collapse;">

                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Image</th>
                <th scope="col">Description</th>
                <th scope="col">Category</th>
                <th scope="col">Delete</th>
                <th scope="col">Update</th>




              
            </tr>
            </thead>
            <tbody>
              {% for product in products %}
              <tr style="text-align: center;border: 1px solid black;border-collapse: collapse;">

                <td>{{product.product_name}}</td>
                <td>{{product.price}}</td>
                <td><img src="/media/{{ product.image }}" alt=""></td>
                <td>{{product.description}}</td>
                <td>{{product.category}}</td>
                <td><a class="btn btn-primary" href="{% url 'seller:update_product' product.id %}">Update</a></td>

                <td><a class="btn btn-danger" href="{% url 'seller:delete_product' product.id %}">Delete</a></td>

              </tr>
              {% endfor %}
              
            </tbody>
          </table>
       </div>
    </div>
</div>
{% endblock %}